const images = { 
    // Logo's
    "logo_white": "images/logos/logo_white.png",
    "logo_blue": "images/logos/logo_blue.png",
    "logo_gold": "images/logos/logo_gold.png",
    "tab_white": "images/logos/tab_white.png",
    "tab_blue": "images/logos/tab_blue.png",
    "tab_gold": "images/logos/tab_gold.png",
    "pencil": "images/pencil2.jpeg",
    // "wave1": "images/wave1.png",
    // "wave2": "images/wave2.png",
    // "wave3": "images/wave3.png",
    // "Blue": "images/home_bg.png",
    "quotes": "images/quotes.png",
    "landingVideo1": "videos/video6.mp4",
    "aboutBg": "images/aboutUs.jpg",
    "ScrollTop": "images/top.png",
    "telephone": "images/contact.jpg",
    // Our Solutions
    "ocab1": "images/ocab1.jpg",
    "ocab2": "images/ocab2.jpg",
    "ocab3": "images/ocab3.jpg",
    "ocab4": "images/ocab4.jpg",
    "ui_ux": "images/ui_ux.png",
    "web_and_mobile": "images/web_and_mobile.png",
    "dbm": "images/dbm.png",
    "infrastructure": "images/infrastructure.png",
    "devops": "images/devops.png",
    "gamification": "images/gamification.png",
    "digital_twin": "images/digital_twin.png",
    "xr": "images/xr.png",
    "first": "images/first.png",
    "kickoff": "images/kickoff.png",
    "expansion": "images/expansion.png",
    "milestone": "images/milestone2.png",
    "innovative": "images/innovative.png",

    "vision": "images/vision.png",
    "da": "images/da.png",
    "actionable": "images/actionable.png",
    // Our Services
    "os1": "images/box_gold.png",
    "os2": "images/monitor_gold.png",
    "os3": "images/bulp_gold.png",
    "pencil2": "images/O9FG4R0.png",
    // Images Our Technologies
    "react": "images/technologies/react.png",
    "html": "images/technologies/html.png",
    "css": "images/technologies/css.png",
    "vue": "images/technologies/vue.png",
    "ruby": "images/technologies/ruby.png",
    "ios": "images/technologies/ios.png",
    "android": "images/technologies/android.png",
    "azure": "images/technologies/azure.png",
    "node": "images/technologies/node.png",
    "redshift": "images/technologies/redshift.png",
    "docker": "images/technologies/docker.png",
    "java": "images/technologies/java.png",
    "mongo": "images/technologies/mongo.png",
    "logoCC": "images/logo_classcover.png"
};

export default images;
