// Subject options for select fields
export const SUBJECT_OPTIONS = [
  { label: "Academic Registrar", value: "Academic Registrar" },
  { label: "American Studies", value: "American Studies" },
  { label: "Arabic", value: "Arabic" },
  { label: "Art and Design", value: "Art and Design" },
  { label: "Biology", value: "Biology" },
  { label: "Business Studies", value: "Business Studies" },
  { label: "Calculus", value: "Calculus" },
  { label: "Careers", value: "Careers" },
  { label: "Chemistry", value: "Chemistry" },
  { label: "Chinese", value: "Chinese" },
  { label: "Citizenship", value: "Citizenship" },
  { label: "Classical Studies", value: "Classical Studies" },
  { label: "Computer Science", value: "Computer Science" },
  { label: "Computer Studies", value: "Computer Studies" },
  { label: "Dance", value: "Dance" },
  { label: "Design Technology", value: "Design Technology" },
  { label: "Drama", value: "Drama" },
  { label: "EAL", value: "EAL" },
  { label: "Early Years", value: "Early Years" },
  { label: "Economics", value: "Economics" },
  { label: "Education", value: "Education" },
  { label: "English", value: "English" },
  {
    label: "English as an Additional Language",
    value: "English as an Additional Language",
  },
  { label: "Environmental Studies", value: "Environmental Studies" },
  { label: "Film Studies", value: "Film Studies" },
  { label: "French", value: "French" },
  { label: "Geography", value: "Geography" },
  { label: "Geology", value: "Geology" },
  { label: "German", value: "German" },
  { label: "Global Perspectives", value: "Global Perspectives" },
  { label: "Health", value: "Health" },
  { label: "History", value: "History" },
  { label: "Home Economics", value: "Home Economics" },
  { label: "Head Teacher", value: "Head Teacher" },
  { label: "House Master", value: "House Master" },
  { label: "House Mistress", value: "House Mistress" },
  { label: "Humanities", value: "Humanities" },
  { label: "ICT", value: "ICT" },
  { label: "Inspector", value: "Inspector" },
  { label: "Japanese", value: "Japanese" },
  { label: "Learning Support", value: "Learning Support" },
  { label: "Legal Studies", value: "Legal Studies" },
  { label: "Librarianship", value: "Librarianship" },
  { label: "Literature", value: "Literature" },
  { label: "Mathematics", value: "Mathematics" },
  { label: "Media Studies", value: "Media Studies" },
  { label: "MFL", value: "MFL" },
  { label: "Middle School Generalist", value: "Middle School Generalist" },
  { label: "Music", value: "Music" },
  { label: "Outdoor Education", value: "Outdoor Education" },
  { label: "Philosophy", value: "Philosophy" },
  { label: "Physical Education", value: "Physical Education" },
  { label: "Physics", value: "Physics" },
  { label: "Politics", value: "Politics" },
  { label: "Primary", value: "Primary" },
  { label: "PSHE", value: "PSHE" },
  { label: "Psychology", value: "Psychology" },
  { label: "Religious Education", value: "Religious Education" },
  { label: "Russian", value: "Russian" },
  { label: "School Counselor", value: "School Counselor" },
  { label: "School Psychologist", value: "School Psychologist" },
  { label: "Science", value: "Science" },
  { label: "Secondary", value: "Secondary" },
  { label: "Social Sciences", value: "Social Sciences" },
  { label: "Sociology", value: "Sociology" },
  { label: "Spanish", value: "Spanish" },
  { label: "Special Needs", value: "Special Needs" },
  { label: "Statistics", value: "Statistics" },
  { label: "Thai", value: "Thai" },
  { label: "Theatre Studies", value: "Theatre Studies" },
  { label: "Theory of Knowledge", value: "Theory of Knowledge" },
];

// Teacher role options for select fields
export const ROLES_OPTIONS = [
  { value: "academic_registrar", label: "Academic registrar" },
  { value: "business_manager", label: "Business manager" },
  { value: "careers_counsellor", label: "Careers Counsellor" },
  { value: "deputy_head_secondary", label: "Deputy Head of Secondary" },
  { value: "deputy_head_school", label: "Deputy Head of School" },
  // Removed duplicate entry for Deputy Head of Primary
  { value: "director", label: "Director" },
  { value: "director_of_studies", label: "Director of Studies" },
  { value: "grade_level_coordinator", label: "Grade level Coordinator" },
  { value: "head_of_department", label: "Head of Department" },
  { value: "head_of_early_years", label: "Head of Early Years" },
  { value: "head_of_prep_school", label: "Head of Prep School" },
  { value: "head_of_primary", label: "Head of Primary" },
  { value: "head_of_secondary", label: "Head of Secondary" },
  { value: "head_of_section", label: "Head of Section" },
  { value: "head_of_subject", label: "Head of Subject" },
  { value: "head_of_year", label: "Head of Year" },
  { value: "head_teacher", label: "Head Teacher" },
  { value: "house_master", label: "House Master" },
  { value: "house_mistress", label: "House Mistress" },
  { value: "ib_coordinator", label: "IB Coordinator" },
  { value: "inspector", label: "Inspector" },
  { value: "phase_coordinator", label: "Phase Coordinator" },
  { value: "principal", label: "Principal" },
  { value: "principal_inspector", label: "Principal Inspector" },
  { value: "psychologist", label: "Psychologist" },
  { value: "second_in_department", label: "Second in Department" },
  { value: "senior_inspector", label: "Senior Inspector" },
  { value: "teacher", label: "Teacher" },
  { value: "vice_director", label: "Vice Director" },
  { value: "vice_principal", label: "Vice Principal" },
];
