<?php
$fabrica_slider_sc = fabrica_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $fabrica_slider_sc ) && strpos( $fabrica_slider_sc, '[' ) !== false && strpos( $fabrica_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( fabrica_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$fabrica_anchor_icon = fabrica_get_theme_option( 'front_page_title_anchor_icon' );
		$fabrica_anchor_text = fabrica_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $fabrica_anchor_icon ) || ! empty( $fabrica_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $fabrica_anchor_icon ) ? ' icon="' . esc_attr( $fabrica_anchor_icon ) . '"' : '' )
									. ( ! empty( $fabrica_anchor_text ) ? ' title="' . esc_attr( $fabrica_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $fabrica_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$fabrica_scheme = fabrica_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $fabrica_scheme ) && ! fabrica_is_inherit( $fabrica_scheme ) ) {
			echo ' scheme_' . esc_attr( $fabrica_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( fabrica_get_theme_option( 'front_page_title_paddings' ) );
		if ( fabrica_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$fabrica_css      = '';
		$fabrica_bg_image = fabrica_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $fabrica_bg_image ) ) {
			$fabrica_css .= 'background-image: url(' . esc_url( fabrica_get_attachment_url( $fabrica_bg_image ) ) . ');';
		}
		if ( ! empty( $fabrica_css ) ) {
			echo ' style="' . esc_attr( $fabrica_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$fabrica_anchor_icon = fabrica_get_theme_option( 'front_page_title_anchor_icon' );
		$fabrica_anchor_text = fabrica_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $fabrica_anchor_icon ) || ! empty( $fabrica_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $fabrica_anchor_icon ) ? ' icon="' . esc_attr( $fabrica_anchor_icon ) . '"' : '' )
									. ( ! empty( $fabrica_anchor_text ) ? ' title="' . esc_attr( $fabrica_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( fabrica_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' fabrica-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$fabrica_css      = '';
			$fabrica_bg_mask  = fabrica_get_theme_option( 'front_page_title_bg_mask' );
			$fabrica_bg_color_type = fabrica_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $fabrica_bg_color_type ) {
				$fabrica_bg_color = fabrica_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $fabrica_bg_color_type ) {
				$fabrica_bg_color = fabrica_get_scheme_color( 'bg_color', $fabrica_scheme );
			} else {
				$fabrica_bg_color = '';
			}
			if ( ! empty( $fabrica_bg_color ) && $fabrica_bg_mask > 0 ) {
				$fabrica_css .= 'background-color: ' . esc_attr(
					1 == $fabrica_bg_mask ? $fabrica_bg_color : fabrica_hex2rgba( $fabrica_bg_color, $fabrica_bg_mask )
				) . ';';
			}
			if ( ! empty( $fabrica_css ) ) {
				echo ' style="' . esc_attr( $fabrica_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$fabrica_caption = fabrica_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $fabrica_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $fabrica_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $fabrica_caption, 'fabrica_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$fabrica_description = fabrica_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $fabrica_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $fabrica_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $fabrica_description ), 'fabrica_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( fabrica_get_theme_option( 'front_page_title_button1_link' ) != '' || fabrica_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						fabrica_show_layout( fabrica_customizer_partial_refresh_front_page_title_button1_link() );
						fabrica_show_layout( fabrica_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
