# Generated by Django 4.2.26 on 2025-12-01 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('english', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('position', models.CharField(choices=[('teacher', 'Teacher'), ('leader', 'Senior Leader'), ('other', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('second_nationality', models.BooleanField(default=False)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('hear_from', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('assistant_teacher', 'Assistant Teacher'), ('senior_leader', 'Senior Leader')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('age_group', models.CharField(blank=True, max_length=50)),
                ('curriculum', models.JSONField(blank=True, default=list)),
                ('leadership_role', models.CharField(blank=True, choices=[('coordinator', 'Coordinator'), ('hod', 'Head of Department'), ('assistant_principal', 'Assistant Principal'), ('principal', 'Principal')], max_length=30, null=True)),
                ('job_alerts', models.BooleanField(default=False)),
                ('available_day', models.CharField(blank=True, max_length=2)),
                ('available_month', models.CharField(blank=True, max_length=2)),
                ('available_year', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'db_table': 'teacher_profiles',
            },
        ),
    ]
