# Generated by Django 4.2.26 on 2025-12-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('school_avatar', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('remote', 'Remote'), ('casual', 'Casual'), ('full-time', 'Full-time'), ('part-time', 'Part-time')], max_length=20)),
                ('school_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('charter', 'Charter'), ('international', 'International')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed')], default='active', max_length=20)),
                ('gender_preference', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='any', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-date_posted'],
            },
        ),
    ]
