# Generated by Django 4.2.26 on 2025-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='curriculum',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='education_stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='international_package',
            field=models.CharField(blank=True, choices=[('to_be_confirmed', 'To Be Confirmed'), ('tax_free', 'Tax Free Salary'), ('competitive', 'Competitive salary based on experience')], max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
