# Generated by Django 4.2.26 on 2025-12-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_stripe_customer_id_user_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='age_group',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='position',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='role',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
