# Generated by Django 4.2.26 on 2025-12-17 09:32

from django.db import migrations, models


def convert_strings_to_json_arrays(apps, schema_editor):
    """Convert existing string values to JSON arrays before changing field types"""
    db_alias = schema_editor.connection.alias
    db_vendor = schema_editor.connection.vendor  # 'sqlite', 'mysql', 'postgresql', etc.

    # Use raw SQL to convert string fields to JSON arrays
    with schema_editor.connection.cursor() as cursor:
        if db_vendor == 'sqlite':
            # SQLite uses json_valid() and json_array()
            for field in ['position', 'role', 'subject', 'age_group']:
                cursor.execute(f"""
                    UPDATE teacher_profiles
                    SET {field} = json_array({field})
                    WHERE {field} IS NOT NULL
                    AND {field} != ''
                    AND json_valid({field}) = 0
                """)

                cursor.execute(f"""
                    UPDATE teacher_profiles
                    SET {field} = '[]'
                    WHERE {field} IS NULL OR {field} = ''
                """)

        elif db_vendor == 'mysql':
            # MySQL uses JSON_VALID() and JSON_ARRAY()
            for field in ['position', 'role', 'subject', 'age_group']:
                cursor.execute(f"""
                    UPDATE teacher_profiles
                    SET {field} = JSON_ARRAY({field})
                    WHERE {field} IS NOT NULL
                    AND {field} != ''
                    AND JSON_VALID({field}) = 0
                """)

                cursor.execute(f"""
                    UPDATE teacher_profiles
                    SET {field} = '[]'
                    WHERE {field} IS NULL OR {field} = ''
                """)

        else:
            # For PostgreSQL or other databases, use Python-based conversion
            TeacherProfile = apps.get_model('app', 'TeacherProfile')
            for profile in TeacherProfile.objects.all():
                for field in ['position', 'role', 'subject', 'age_group']:
                    value = getattr(profile, field)
                    if value and not (isinstance(value, list) or (isinstance(value, str) and value.startswith('['))):
                        setattr(profile, field, [value])
                    elif not value:
                        setattr(profile, field, [])
                profile.save()


def reverse_json_arrays_to_strings(apps, schema_editor):
    """Convert JSON arrays back to strings on rollback"""
    db_vendor = schema_editor.connection.vendor

    with schema_editor.connection.cursor() as cursor:
        if db_vendor == 'sqlite':
            # SQLite uses json_extract()
            for field in ['position', 'role', 'subject', 'age_group']:
                cursor.execute(f"""
                    UPDATE teacher_profiles
                    SET {field} = COALESCE(json_extract({field}, '$[0]'), '')
                    WHERE json_valid({field})
                """)

        elif db_vendor == 'mysql':
            # MySQL uses JSON_EXTRACT()
            for field in ['position', 'role', 'subject', 'age_group']:
                cursor.execute(f"""
                    UPDATE teacher_profiles
                    SET {field} = COALESCE(JSON_UNQUOTE(JSON_EXTRACT({field}, '$[0]')), '')
                    WHERE JSON_VALID({field})
                """)

        else:
            # For PostgreSQL or other databases, use Python-based conversion
            TeacherProfile = apps.get_model('app', 'TeacherProfile')
            for profile in TeacherProfile.objects.all():
                for field in ['position', 'role', 'subject', 'age_group']:
                    value = getattr(profile, field)
                    if isinstance(value, list) and len(value) > 0:
                        setattr(profile, field, value[0])
                    else:
                        setattr(profile, field, '')
                profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_stripe_customer_id_user_stripe_subscription_id_and_more'),
    ]

    operations = [
        # First, convert existing data
        migrations.RunPython(
            convert_strings_to_json_arrays,
            reverse_json_arrays_to_strings
        ),
        # Then, alter the field types
        migrations.AlterField(
            model_name='teacherprofile',
            name='age_group',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='position',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='role',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
