# Generated by Django 4.2.26 on 2025-12-17 09:58

from django.db import migrations, models


def convert_boolean_to_string(apps, schema_editor):
    """
    Set all Boolean values to False before changing field type.
    The field alteration will handle the conversion.
    """
    # Set all values to False (0) - the AlterField will handle the type conversion
    # Users will need to re-enter their second nationality
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE teacher_profiles
            SET second_nationality = 0
        """)


def reverse_string_to_boolean(apps, schema_editor):
    """Convert string values back to Boolean on rollback"""
    # On rollback, set any non-empty string to True (1), empty/null to False (0)
    with schema_editor.connection.cursor() as cursor:
        # Set all to False first
        cursor.execute("""
            UPDATE teacher_profiles
            SET second_nationality = 0
        """)

        # Then set non-empty strings to True
        cursor.execute("""
            UPDATE teacher_profiles
            SET second_nationality = 1
            WHERE second_nationality IS NOT NULL
            AND second_nationality != ''
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_convert_teacherprofile_to_arrays'),
    ]

    operations = [
        # First convert the data while it's still a Boolean field
        migrations.RunPython(
            convert_boolean_to_string,
            reverse_string_to_boolean
        ),
        # Then change the field type
        migrations.AlterField(
            model_name='teacherprofile',
            name='second_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
