# Generated by Django 4.2.26 on 2025-12-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_change_second_nationality_to_charfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='role',
            new_name='roles',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='subject',
            new_name='subjects',
        ),
    ]
