# Generated by Django 4.2.26 on 2025-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_role_subject_to_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('deputy_principal', 'Deputy Principal'), ('head_of_school', 'Head of School')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='school_type',
            field=models.CharField(choices=[('public', 'Public'), ('international', 'International')], max_length=20),
        ),
    ]
