# Generated by Django 4.2.26 on 2025-12-19 10:31

from django.db import migrations, models
import json


def convert_leadership_role_to_array(apps, schema_editor):
    """Convert existing string leadership_role values to arrays"""
    TeacherProfile = apps.get_model('app', 'TeacherProfile')
    for profile in TeacherProfile.objects.all():
        if profile.leadership_role and profile.leadership_role.strip():
            # Convert single string value to array with one element
            profile.leadership_role = json.dumps([profile.leadership_role])
        else:
            # Convert empty/null to empty array
            profile.leadership_role = json.dumps([])
        profile.save()


def convert_availability_to_date(apps, schema_editor):
    """Convert available_day/month/year to available_date"""
    TeacherProfile = apps.get_model('app', 'TeacherProfile')
    from datetime import date
    for profile in TeacherProfile.objects.all():
        if profile.available_day and profile.available_month and profile.available_year:
            try:
                # Create date from day, month, year
                profile.available_date = date(
                    int(profile.available_year),
                    int(profile.available_month),
                    int(profile.available_day)
                )
                profile.save()
            except (ValueError, TypeError):
                # If date is invalid, leave available_date as null
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_phone'),
    ]

    operations = [
        # First, add the new available_date field
        migrations.AddField(
            model_name='teacherprofile',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
        # Convert the old availability fields to the new date field
        migrations.RunPython(convert_availability_to_date, migrations.RunPython.noop),
        # Remove old availability fields
        migrations.RemoveField(
            model_name='teacherprofile',
            name='available_day',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='available_month',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='available_year',
        ),
        # Convert leadership_role strings to arrays before changing field type
        migrations.RunPython(convert_leadership_role_to_array, migrations.RunPython.noop),
        # Now change the field type to JSONField
        migrations.AlterField(
            model_name='teacherprofile',
            name='leadership_role',
            field=models.JSONField(blank=True, default=list),
        ),
        # Add package field to Job
        migrations.AddField(
            model_name='job',
            name='package',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
