# Generated by Django 4.2.26 on 2025-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_teacherprofile_available_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_invitation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
