# Generated by Django 4.2.26 on 2025-12-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_jobapplication_interview_invitation_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
    ]
