# Generated by Django 4.2.26 on 2025-12-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_job_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_weekly_summary',
            field=models.BooleanField(default=True),
        ),
    ]
