# Generated by Django 4.2.26 on 2025-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_receive_weekly_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(max_length=100),
        ),
    ]
