# Generated by Django 4.2.26 on 2026-01-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, default='launch', max_length=100)),
            ],
            options={
                'verbose_name': 'Welcome Email Log',
                'verbose_name_plural': 'Welcome Email Logs',
                'db_table': 'welcome_email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='welcome_ema_email_038f43_idx'), models.Index(fields=['campaign_name'], name='welcome_ema_campaig_546626_idx')],
            },
        ),
    ]
