# Generated by Django 4.2.26 on 2026-01-12 08:43

from django.db import migrations, models
import json


def convert_curriculum_to_array(apps, schema_editor):
    """Convert existing curriculum CharField values to JSONField arrays"""
    Job = apps.get_model('app', 'Job')
    for job in Job.objects.all():
        if job.curriculum:
            # If it's a string, convert to array with single element
            if isinstance(job.curriculum, str):
                job.curriculum = [job.curriculum] if job.curriculum.strip() else []
                job.save(update_fields=['curriculum'])
        else:
            # Empty string becomes empty array
            job.curriculum = []
            job.save(update_fields=['curriculum'])


def reverse_curriculum_to_string(apps, schema_editor):
    """Convert JSONField arrays back to CharField strings"""
    Job = apps.get_model('app', 'Job')
    for job in Job.objects.all():
        if job.curriculum and isinstance(job.curriculum, list):
            # Convert array to comma-separated string
            job.curriculum = ', '.join(job.curriculum) if job.curriculum else ''
            job.save(update_fields=['curriculum'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_welcomeemaillog'),
    ]

    operations = [
        # First, add a temporary field to hold the data
        migrations.AddField(
            model_name='job',
            name='curriculum_temp',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        # Copy and convert data from old field to new field
        migrations.RunPython(
            lambda apps, schema_editor: convert_curriculum_to_temp(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        # Remove old field
        migrations.RemoveField(
            model_name='job',
            name='curriculum',
        ),
        # Rename temp field to curriculum
        migrations.RenameField(
            model_name='job',
            old_name='curriculum_temp',
            new_name='curriculum',
        ),
    ]


def convert_curriculum_to_temp(apps, schema_editor):
    """Copy curriculum data from CharField to temporary JSONField"""
    Job = apps.get_model('app', 'Job')
    for job in Job.objects.all():
        if hasattr(job, 'curriculum') and job.curriculum:
            # Convert string to array with single element
            curriculum_value = job.curriculum.strip() if job.curriculum else ''
            job.curriculum_temp = [curriculum_value] if curriculum_value else []
        else:
            job.curriculum_temp = []
        job.save(update_fields=['curriculum_temp'])
