# Generated by Django 4.2.26 on 2026-01-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_welcomeemaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='curriculum',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
