import os
import django
from datetime import date, timedelta

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from app.models import Job

# Clear existing jobs
Job.objects.all().delete()

# Sample job data
sample_jobs = [
    {
        'title': 'Mathematics Teacher - High School',
        'school_name': 'Springfield International School',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'New York, USA',
        'job_type': 'full-time',
        'school_type': 'international',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'We are seeking an experienced Mathematics teacher for our high school program.',
        'description': 'Join our dynamic team of educators at Springfield International School. We are looking for a passionate Mathematics teacher who can inspire students and deliver engaging lessons.',
        'requirements': 'Bachelor\'s degree in Mathematics or Education\n5+ years teaching experience\nIB curriculum experience preferred',
        'level': 'High School (Grades 9-12)',
        'subjects': ['Mathematics', 'Algebra', 'Calculus'],
        'closing_date': date.today() + timedelta(days=30),
    },
    {
        'title': 'English Language Teacher',
        'school_name': 'Global Academy',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'London, UK',
        'job_type': 'remote',
        'school_type': 'private',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'Remote English teaching position available.',
        'description': 'Global Academy is seeking an English Language teacher for remote teaching. This position offers flexibility and the opportunity to work with international students.',
        'requirements': 'TEFL/TESOL certification\nExcellent communication skills\nExperience with online teaching platforms',
        'level': 'Middle School (Grades 6-8)',
        'subjects': ['English', 'Literature'],
        'closing_date': date.today() + timedelta(days=45),
    },
    {
        'title': 'Science Teacher - Biology & Chemistry',
        'school_name': 'Riverside Charter School',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'San Francisco, USA',
        'job_type': 'full-time',
        'school_type': 'charter',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'Science teacher needed for Biology and Chemistry.',
        'description': 'Riverside Charter School is looking for an enthusiastic Science teacher to teach Biology and Chemistry to high school students.',
        'requirements': 'Master\'s degree in Science Education\nStrong lab management skills\nPassion for student-centered learning',
        'level': 'High School (Grades 9-12)',
        'subjects': ['Biology', 'Chemistry', 'Science'],
        'closing_date': date.today() + timedelta(days=20),
    },
    {
        'title': 'Elementary School Teacher',
        'school_name': 'Sunshine Elementary',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'Sydney, Australia',
        'job_type': 'part-time',
        'school_type': 'public',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'Part-time elementary teacher position.',
        'description': 'We need a dedicated elementary teacher to join our team. This is a part-time position ideal for experienced educators.',
        'requirements': 'Teaching certification\nExperience with young learners\nPatient and creative approach',
        'level': 'Elementary (Grades 1-5)',
        'subjects': ['General Education'],
        'closing_date': date.today() + timedelta(days=15),
    },
    {
        'title': 'Substitute Teacher',
        'school_name': 'Metro Public Schools',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'Chicago, USA',
        'job_type': 'casual',
        'school_type': 'public',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'Casual substitute teacher needed.',
        'description': 'Metro Public Schools is building a pool of qualified substitute teachers for various subjects and grade levels.',
        'requirements': 'Bachelor\'s degree\nFlexible schedule\nAbility to adapt to different classrooms',
        'level': 'All Grades',
        'subjects': ['Various'],
        'closing_date': date.today() + timedelta(days=60),
    },
    {
        'title': 'History Teacher - Middle School',
        'school_name': 'Heritage Academy',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'Boston, USA',
        'job_type': 'full-time',
        'school_type': 'private',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'Middle school History teacher position.',
        'description': 'Heritage Academy seeks a passionate History teacher to engage middle school students in understanding world and American history.',
        'requirements': 'History degree required\nEngaging teaching style\nExperience with project-based learning',
        'level': 'Middle School (Grades 6-8)',
        'subjects': ['History', 'Social Studies'],
        'closing_date': date.today() + timedelta(days=25),
    },
    {
        'title': 'Physical Education Teacher',
        'school_name': 'Athletic Prep School',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'Los Angeles, USA',
        'job_type': 'full-time',
        'school_type': 'private',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'PE teacher for sports-focused school.',
        'description': 'Athletic Prep School is looking for an energetic Physical Education teacher who can develop athletic skills and promote healthy lifestyles.',
        'requirements': 'Degree in Physical Education\nCoaching experience\nFirst Aid certified',
        'level': 'High School (Grades 9-12)',
        'subjects': ['Physical Education', 'Sports'],
        'closing_date': date.today() + timedelta(days=35),
    },
    {
        'title': 'Music Teacher',
        'school_name': 'Harmony Arts School',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'Nashville, USA',
        'job_type': 'part-time',
        'school_type': 'private',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'Part-time Music teacher needed.',
        'description': 'Harmony Arts School is seeking a talented Music teacher to inspire students and lead our music program.',
        'requirements': 'Music degree or equivalent\nInstrument proficiency\nPerformance experience',
        'level': 'All Grades',
        'subjects': ['Music', 'Choir', 'Band'],
        'closing_date': date.today() + timedelta(days=40),
    },
    {
        'title': 'Special Education Teacher',
        'school_name': 'Inclusive Learning Center',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'Toronto, Canada',
        'job_type': 'full-time',
        'school_type': 'public',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'Special Education teacher position.',
        'description': 'Join our inclusive team as a Special Education teacher. We support students with diverse learning needs.',
        'requirements': 'Special Education certification\nExperience with IEPs\nPatient and compassionate',
        'level': 'Elementary (Grades 1-5)',
        'subjects': ['Special Education'],
        'closing_date': date.today() + timedelta(days=50),
    },
    {
        'title': 'Computer Science Teacher',
        'school_name': 'Tech Valley High',
        'school_avatar': 'https://via.placeholder.com/100',
        'location': 'Seattle, USA',
        'job_type': 'full-time',
        'school_type': 'public',
        'status': 'active',
        'gender_preference': 'any',
        'summary': 'Computer Science teacher for tech-focused school.',
        'description': 'Tech Valley High is looking for a Computer Science teacher to teach programming, web development, and digital literacy.',
        'requirements': 'CS degree or related field\nProgramming experience\nPassion for technology education',
        'level': 'High School (Grades 9-12)',
        'subjects': ['Computer Science', 'Programming', 'Web Development'],
        'closing_date': date.today() + timedelta(days=28),
    },
]

# Create jobs
for job_data in sample_jobs:
    Job.objects.create(**job_data)

print(f"Successfully created {len(sample_jobs)} sample jobs!")
